server:
  port: 8100
spring:
  application:
    name: cloud-api
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: 192.168.127.137
    port: 6379
    database: 0
    timeout: 1800000
